### PR TITLE
add const-constructed builder args

### PR DESCRIPTION
**Pull request by davidhewitt**
Adds a `const BUILDER_ARGS` which allows `create_type_object` to become concrete.

### CODE REVIEW

**Comment by vultix** [comment]
I'm not a huge fan of this, primarily because it tightly couples the behavior of building a type to the `PyTypeBuilderArgs`.  

When building a metaclass, I'll want to use a very different set of builder parameters, and the `PyTypeBuilderArgs` isn't going to be sufficient.  The specific enum variant subclasses will also have subtly different use cases for the type builder.

What benefit does the extra trait add over the existing case of just using the builder? I imagine we could create an API like this that has the same benefit of minimal machine code being generated, but allows for more flexibility of generating other types with the builder.
```rust
impl<T: PyClass> TypeBuilder for T {
    fn build_type(builder: PyTypeBuilder) -> *mut ffi::PyTypeObject {
        builder
            .with_type_doc(T::DOC)
            .with_offsets(T::dict_offset(), T::weaklist_offset())
            .with_slot(ffi::Py_tp_base, T::BaseType::type_object_raw(py))
            .with_slot(ffi::Py_tp_dealloc, tp_dealloc::<T> as *mut c_void)
            .set_is_basetype(T::IS_BASETYPE)
            .set_is_mapping(T::IS_MAPPING)
            .with_class_items(T::items_iter())
            .build(py, T::NAME, T::MODULE, std::mem::size_of::<T::Layout>())
    }
}
```

**Comment by vultix** [comment]
If the worry is about codegen costs and needing to recreate the builder for every monomorphization of `T: PyClass`, I can create a microbenchmark to look into it.  I don't expect it'll be a problem, as the builder itself should be the bulk of codegen now, not the usage of the builder

**Comment by vultix** [comment]
Alright, to test out extra codegen time, I wrote a very simple microbenchmark that generates 300 pyclass impls.  Here's what I found:

| Command         | Variant                      | Build Time (Incremental) | File Size |
|-----------------|------------------------------|--------------------------|-----------|
| build           | main branch                  | 1.51s                    | 3.3MB     |
| build --release | main branch                  | 2.16s                    | 852KB     |
| build           | With `const BUILDER_ARGS`    | 1.57s                    | 3.3MB     |
| build --release | With `const BUILDER_ARGS`    | 1.93s                    | 842KB     |
| build           | Without `const BUILDER_ARGS` | 1.46s                    | 3.4MB     |
| build --release | Without `const BUILDER_ARGS` | 2.57s                    | 965KB     |

The incremental build time is the average of 5 builds each, renaming one of the pyclasses to cause the incremental rebuild.  It does appear using `const BUILDER_ARGS` does slightly reduce the amount of codegen done, which makes sense.

I feel I'm incapable of judging if the extra codegen is a problem, and don't have a better guess as how to measure it.  @davidhewitt thoughts?

**Comment by vultix** [comment]
If you still feel this PR is the way to go, I definitely understand your concern and am happy to merge it.  I'll find a good way to handle the enum use case on top of this

**Comment by davidhewitt** [comment]
Yes, agreed the coupling was not ideal; I figured that this could be a starting point for constifying away the codegen cost (and build size).

Thanks for running the microbenchmark. What I conclude from that is that it definitely is worth constifying eventually for bigger projects, but there's not such a significant regression here that it's a blocker for merge. I'll close this for now and let's go the other way around; once the enum implementation is complete we can work on optimisations like this.

**Pull request closed without merging**
